### PR TITLE
Add us-east-1 as a valid location in shipit (native cloud implementat…

### PR DESCRIPTION
**Pull request by jtolsma**
Add us-east-1 as a valid location in shipit, needed for barges in native accounts to setup load balancers different

### CODE REVIEW

**Comment by wilsonodk** [comment]
I like the change, but it is failing in Circle (I think it's because of version conflicts)

**Comment by jkurz** [comment]
@jtolsma can you fix the broken test here? Then we can merge this. Or is this PR still needed?

**Comment by jkurz** [comment]
Had to play around with the build a bit to get it passing. Turns out we had some parallelism going on in our build, which was causing commands to fire twice. I turned the parallelism down to 1 and things started working again. Going to merge this in.

**Comment by jkurz** [comment]
Closing this because it was originally branched from master actually. I created a new PR here https://github.com/turnerlabs/shipit-api/pull/27

**Pull request closed without merging**
