### PR TITLE
Use docker locally

### PR DESCRIPTION
**Pull request by jkurz**
* I think a lot of people have become really fond of running and developing applications in docker
* this gives us a Dockerfile that will build everything in docker, so we can test the app locally without installing npm modules on our own machine

### CODE REVIEW

**Review by jtolsma — APPROVED** [review]

**Review by wilsonodk — CHANGES_REQUESTED** [review]
Maybe update the `build` script in `package.json` to use this Dockerfile versus the standard one? 

I've been doing this for local development…
```
$ npm run build # Does a Docker build tagged with version
$ npm run local # Does a Docker run with correct env vars
```

**Comment by jkurz** [comment]
@wilsonodk made the update you requested.

**Comment by jkurz** [comment]
Honestly it would be nice if we updated circle.yml to just build everything in docker, and we thought of a sweet way to run the tests outside of docker possibly? Or maybe we do a docker run npm test or something like that, and pass in all the variables to hit the local postgres. But that could be a next step, this just allows for easy dev, without installing all the modules. Wow I never thought I would say that. Honestly it is a little slower, as you have to rebuild docker every time you make a change, so I would still prefer running node locally if you were doing big changes.

**Review by wilsonodk — APPROVED** [review]
💥

**Pull request merged**
